@php
    $listMenu = [
        [
            'id' => 'keuangan',
            'idSidebar' => 'Keuangan',
            'label' => 'Keuangan',
            'icon' => 'ri-file-list-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'labarugi',
                    'label' => 'Laba Rugi',
                    'icon' => null,
                    'route' => route('admin.laporan.keuangan.laba-rugi'),
                    'active' => 'admin.laporan.keuangan.laba-rugi',
                    'permissions' => ['admin.laporan.keuangan.laba-rugi'],
                    'children' => null,
                ],
            ],
        ],
        [
            'id' => 'persediaan',
            'idSidebar' => 'Persediaan',
            'label' => 'Persediaan',
            'icon' => 'ri-file-list-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'kartustok',
                    'label' => 'Kartu Stok',
                    'icon' => null,
                    'route' => route('admin.laporan.persediaan.kartu-stok'),
                    'active' => 'admin.laporan.persediaan.kartu-stok',
                    'permissions' => ['admin.laporan.persediaan.kartu-stok'],
                    'children' => null,
                ],
                [
                    'id' => 'stokpertanggal',
                    'label' => 'Stok Per Tanggal',
                    'icon' => null,
                    'route' => route('admin.laporan.persediaan.stok-per-tanggal'),
                    'active' => 'admin.laporan.persediaan.stok-per-tanggal',
                    'permissions' => ['admin.laporan.persediaan.stok-per-tanggal'],
                    'children' => null,
                ],
                [
                    'id' => 'pergerakanstok',
                    'label' => 'Pergerakan Stok',
                    'icon' => null,
                    'route' => route('admin.laporan.persediaan.pergerakan-stok'),
                    'active' => 'admin.laporan.persediaan.pergerakan-stok',
                    'permissions' => ['admin.laporan.persediaan.pergerakan-stok'],
                    'children' => null,
                ],
                [
                    'id' => 'nilaipersediaan',
                    'label' => 'Nilai Persediaan',
                    'icon' => null,
                    'route' => route('admin.laporan.persediaan.nilai-persediaan'),
                    'active' => 'admin.laporan.persediaan.nilai-persediaan',
                    'permissions' => ['admin.laporan.persediaan.nilai-persediaan'],
                    'children' => null,
                ],
                [
                    'id' => 'mutasinilaipersediaan',
                    'label' => 'Mutasi Nilai Persediaan',
                    'icon' => null,
                    'route' => route('admin.laporan.persediaan.mutasi-nilai-persediaan'),
                    'active' => 'admin.laporan.persediaan.mutasi-nilai-persediaan',
                    'permissions' => ['admin.laporan.persediaan.mutasi-nilai-persediaan'],
                    'children' => null,
                ],
            ],
        ],
        [
            'id' => 'pembelian',
            'idSidebar' => 'Pembelian',
            'label' => 'Pembelian',
            'icon' => 'ri-file-list-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'fakturpembelian',
                    'label' => 'Faktur Pembelian',
                    'icon' => null,
                    'route' => route('admin.laporan.pembelian.faktur-pembelian'),
                    'active' => 'admin.laporan.pembelian.faktur-pembelian',
                    'permissions' => ['admin.laporan.pembelian.faktur-pembelian'],
                    'children' => null,
                ],
            ],
        ],
        [
            'id' => 'penjualan',
            'idSidebar' => 'Penjualan',
            'label' => 'Penjualan',
            'icon' => 'ri-file-list-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'penjualan',
                    'label' => 'Penjualan',
                    'icon' => null,
                    'route' => route('admin.laporan.penjualan.penjualan'),
                    'active' => 'admin.laporan.penjualan.penjualan',
                    'permissions' => ['admin.laporan.penjualan.penjualan'],
                    'children' => null,
                ],
                [
                    'id' => 'pesananpenjualanpersales',
                    'label' => 'Pesanan Penjualan per Sales',
                    'icon' => null,
                    'route' => route('admin.laporan.penjualan.pesanan-penjualan-per-sales'),
                    'active' => 'admin.laporan.penjualan.pesanan-penjualan-per-sales',
                    'permissions' => ['admin.laporan.penjualan.pesanan-penjualan-per-sales'],
                    'children' => null,
                ],
            ],
        ],
    ];
@endphp

<x-admin::utils.menu :title="'Laporan'" :list-menu="$listMenu" />
