@php
    $listMenu = [
        [
            'id' => 'masterproduk',
            'idSidebar' => 'MasterProduk',
            'label' => 'Produk',
            'icon' => 'ri-shopping-bag-3-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'produk',
                    'label' => 'Produk',
                    'icon' => null,
                    'route' => route('admin.master.produk.index'),
                    'active' => 'admin.master.produk.*',
                    'permissions' => ['admin.master.produk', 'admin.master.produk.index'],
                    'children' => null,
                ],
                [
                    'id' => 'kategoriproduk',
                    'label' => 'Kategori Produk',
                    'icon' => null,
                    'route' => route('admin.master.kategori-produk.index'),
                    'active' => 'admin.master.kategori-produk.*',
                    'permissions' => ['admin.master.kategori-produk', 'admin.master.kategori-produk.index'],
                    'children' => null,
                ],
                [
                    'id' => 'jenisproduk',
                    'label' => 'Jenis Produk',
                    'icon' => null,
                    'route' => route('admin.master.jenis-produk.index'),
                    'active' => 'admin.master.jenis-produk.*',
                    'permissions' => ['admin.master.jenis-produk', 'admin.master.jenis-produk.index'],
                    'children' => null,
                ],
                [
                    'id' => 'modelproduk',
                    'label' => 'Model Produk',
                    'icon' => null,
                    'route' => route('admin.master.model-produk.index'),
                    'active' => 'admin.master.model-produk.*',
                    'permissions' => ['admin.master.model-produk', 'admin.master.model-produk.index'],
                    'children' => null,
                ],
            ],
        ],
        [
            'id' => 'masterumum',
            'idSidebar' => 'MasterUmum',
            'label' => 'Umum',
            'icon' => 'ri-settings-4-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'customer',
                    'label' => 'Customer',
                    'icon' => null,
                    'route' => route('admin.master.customer.index'),
                    'active' => 'admin.master.customer.*',
                    'permissions' => ['admin.master.customer', 'admin.master.customer.index'],
                    'children' => null,
                ],
                [
                    'id' => 'supplier',
                    'label' => 'Supplier',
                    'icon' => null,
                    'route' => route('admin.master.supplier.index'),
                    'active' => 'admin.master.supplier.*',
                    'permissions' => ['admin.master.supplier', 'admin.master.supplier.index'],
                    'children' => null,
                ],
                [
                    'id' => 'karyawan',
                    'label' => 'Salesman',
                    'icon' => null,
                    'route' => route('admin.master.karyawan.index'),
                    'active' => 'admin.master.karyawan.*',
                    'permissions' => ['admin.master.karyawan', 'admin.master.karyawan.index'],
                    'children' => null,
                ],
            ],
        ],
        [
            'id' => 'masterpromo',
            'idSidebar' => 'MasterPromo',
            'label' => 'Promo',
            'icon' => 'ri-shopping-bag-3-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'promo',
                    'label' => 'Tier Diskon',
                    'icon' => null,
                    'route' => route('admin.master.promo.index'),
                    'active' => 'admin.master.promo.*',
                    'permissions' => ['admin.master.promo', 'admin.master.promo.index'],
                    'children' => null,
                ],
            ],
        ],
    ];
@endphp

<x-admin::utils.menu :title="'Master'" :list-menu="$listMenu" />
