@php
    $listMenu = [
        [
            'id' => 'transaksi_pembelian',
            'idSidebar' => 'TransaksiPembelian',
            'label' => 'Pembelian',
            'icon' => 'ri-download-2-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'pesananpembelian',
                    'label' => 'PO Pembelian',
                    'icon' => null,
                    'route' => route('admin.pembelian.pesanan-pembelian.index'),
                    'active' => 'admin.pembelian.pesanan-pembelian.*',
                    'permissions' => ['admin.pembelian.pesanan-pembelian', 'admin.pembelian.pesanan-pembelian.index'],
                    'children' => null,
                ],
                [
                    'id' => 'returpembelian',
                    'label' => 'Retur Pembelian',
                    'icon' => null,
                    'route' => route('admin.pembelian.retur-pembelian.index'),
                    'active' => 'admin.pembelian.retur-pembelian.*',
                    'permissions' => ['admin.pembelian.retur-pembelian', 'admin.pembelian.retur-pembelian.index'],
                    'children' => null,
                ],
            ],
        ],
        [
            'id' => 'transaksi_penjualan',
            'idSidebar' => 'TransaksiPenjualan',
            'label' => 'Penjualan',
            'icon' => 'ri-upload-2-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'pesananpenjualan',
                    'label' => 'Pesanan Penjualan',
                    'icon' => null,
                    'route' => route('admin.penjualan.pesanan-penjualan.index'),
                    'active' => 'admin.penjualan.pesanan-penjualan.*',
                    'permissions' => ['admin.penjualan.pesanan-penjualan', 'admin.penjualan.pesanan-penjualan.index'],
                    'children' => null,
                ],
                [
                    'id' => 'suratjalan',
                    'label' => 'Surat Jalan',
                    'icon' => null,
                    'route' => route('admin.penjualan.surat-jalan.index'),
                    'active' => 'admin.penjualan.surat-jalan.*',
                    'permissions' => ['admin.penjualan.surat-jalan.index'],
                    'children' => null,
                ],
                [
                    'id' => 'fakturpenjualanviasj',
                    'label' => 'Faktur Penjualan Via SJ',
                    'icon' => null,
                    'route' => route('admin.penjualan.faktur-penjualan-via-sj.index'),
                    'active' => 'admin.penjualan.faktur-penjualan-via-sj.*',
                    'permissions' => ['admin.penjualan.faktur-penjualan-via-sj.index'],
                    'children' => null,
                ],
                [
                    'id' => 'fakturpenjualanviaso',
                    'label' => 'Faktur Penjualan Via SO',
                    'icon' => null,
                    'route' => route('admin.penjualan.faktur-penjualan-via-so.index'),
                    'active' => 'admin.penjualan.faktur-penjualan-via-so.*',
                    'permissions' => ['admin.penjualan.faktur-penjualan-via-so.index'],
                    'children' => null,
                ],
                [
                    'id' => 'fakturpenjualan',
                    'label' => 'Faktur Penjualan',
                    'icon' => null,
                    'route' => route('admin.penjualan.faktur-penjualan.index'),
                    'active' => 'admin.penjualan.faktur-penjualan.*',
                    'permissions' => ['admin.penjualan.faktur-penjualan', 'admin.penjualan.faktur-penjualan.index'],
                    'children' => null,
                ],
                // [
                //     'id' => 'returpenjualan',
                //     'label' => 'Retur Penjualan',
                //     'icon' => null,
                //     'route' => route('admin.penjualan.retur-penjualan.index'),
                //     'active' => 'admin.penjualan.retur-penjualan.*',
                //     'permissions' => ['admin.penjualan.retur-penjualan', 'admin.penjualan.retur-penjualan.index'],
                //     'children' => null,
                // ],
            ],
        ],
        [
            'id' => 'transaksi_persediaan',
            'idSidebar' => 'TransaksiPersediaan',
            'label' => 'Persediaan',
            'icon' => 'ri-gift-2-fill',
            'route' => null,
            'active' => null,
            'permissions' => null,
            'children' => [
                [
                    'id' => 'persediaan',
                    'label' => 'Persediaan',
                    'icon' => null,
                    'route' => route('admin.persediaan.persediaan.index'),
                    'active' => 'admin.persediaan.persediaan.*',
                    'permissions' => ['admin.persediaan.persediaan', 'admin.persediaan.persediaan.index'],
                    'children' => null,
                ],
                [
                    'id' => 'penyesuaiantambah',
                    'label' => 'Penyesuaian Tambah',
                    'icon' => null,
                    'route' => route('admin.persediaan.penambahan-persediaan.index'),
                    'active' => 'admin.persediaan.penambahan-persediaan.*',
                    'permissions' => [
                        'admin.persediaan.penambahan-persediaan',
                        'admin.persediaan.penambahan-persediaan.index',
                    ],
                    'children' => null,
                ],
                [
                    'id' => 'penyesuaiankurang',
                    'label' => 'Penyesuaian Kurang',
                    'icon' => null,
                    'route' => route('admin.persediaan.pengurangan-persediaan.index'),
                    'active' => 'admin.persediaan.pengurangan-persediaan.*',
                    'permissions' => [
                        'admin.persediaan.pengurangan-persediaan',
                        'admin.persediaan.pengurangan-persediaan.index',
                    ],
                    'children' => null,
                ],
            ],
        ],
    ];
@endphp

<x-admin::utils.menu :title="'Transaksi'" :list-menu="$listMenu" />
